<a id="top"></a>

### Contents
- [01 - Numpy Package](#section-1) 
- [02 - Creating a Numpy Array](#section-2) 
- [03 - Arithmetic with Numpy Array](#section-3) 
- [04 - Indexing and Slicing a Numpy Array](#section-4)
- [05 - Universal Functions](#section-5)  
- [06 - Array Oriented Programming with Arrays](#section-6)
- [07 - Linear Algebra](#section-7) 
- [08 - Pseudorandom Number Generation](#section-8)

<a id="section-1"></a>
<details open> 
<summary> 01 - Numpy Package </summary> 
</details>

In [1]:
try:
    import numpy
except ImportError:
    !pip install numpy
else:
    import numpy as np


[Back to Contents](#top)

<a id="section-2"></a>
<details open> 
<summary> 02 - Creating a Numpy Array </summary> <br>
    <li> Attributes of a simple Numpy array - shape, ndim, dtype
    <li> Creating a Numpy arry using functions 
</details>

In [2]:
''' Attributes of a simple Numpy array - shape, ndim, dtype
    shape - rows and columns
    ndim - number of dimensions
    dtype - data type
'''

test = np.array([1, 2, 3])

print(test.shape)
print(test.ndim)
print(test.dtype)

(3,)
1
int64


<b> Some important NumPy array creation functions

|Function|	Description|
|---------|--------------|
|array|	Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default
|asarray|	Convert input to ndarray, but do not copy if the input is already an ndarray
|arange|	Like the built-in range but returns an ndarray instead of a list
|ones, ones_like|	Produce an array of all 1s with the given shape and data type; ones_like takes another array and produces a ones array of the same shape and data type
|zeros, zeros_like|	Like ones and ones_like but producing arrays of 0s instead
|empty, empty_like|	Create new arrays by allocating new memory, but do not populate with any values like ones and zeros
|full, full_like|	Produce an array of the given shape and data type with all values set to the indicated "fill value"; full_like takes another array and produces a filled array of the same shape and data type
|eye, identity|	Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)

In [3]:
# 1) Using array() function

test = np.array([1, 2, 3])
print(test)

[1 2 3]


In [4]:
# 2) Using arange() function

test = np.arange(10) #arange is numpy equivalent of range()
print(test)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# 3) Using ones() function

test = np.ones((2, 3))
print(test)


[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# 4) Using zeros() function

test = np.zeros((2, 3)) #input is tuple which indicates shape - rows and columns
print(test)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# 5) Using empty() function

new_test = np.empty((2, 3)) #empty does not return an array with 0s
print(new_test)


[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# 6) Using full() function

full_example = np.full((2, 3), 10) #filling an numpy array with a particular shape with a given value
print(full_example)


[[10 10 10]
 [10 10 10]]


In [9]:
# 7) Using eye() function

eye_example = np.eye(3) #identity matrix
print(eye_example)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<b>NumPy data types

|Type|	Type code|	Description|
|---|------|--------------|
|int8, uint8|	i1, u1	|Signed and unsigned 8-bit (1 byte) integer types
|int16, uint16|	i2, u2|	Signed and unsigned 16-bit integer types
|int32, uint32|	i4, u4|	Signed and unsigned 32-bit integer types
|int64, uint64|	i8, u8|	Signed and unsigned 64-bit integer types
|float16|	f2|Half-precision floating point
|float32|	f4 or f|	Standard single-precision floating point; compatible with C float
|float64|	f8 or d|	Standard double-precision floating point; compatible with C double and Python float object
|float128|	f16 or g|	Extended-precision floating point
|complex64, complex128, complex256	|c8, c16, c32|	Complex numbers represented by two 32, 64, or 128 floats, respectively
|bool	|?|	Boolean type storing True and False values
|object	|O|	Python object type; a value can be any Python object
|string_	|S|	Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use 'S10'
|unicode_	|U|	Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., 'U10')

In [10]:
# Changing data type using astype()

new_test = np.arange(10.0, 20.9)
print('Original new_test array: ', new_test)

print('\nOriginal test array: \n', test)
result = test.astype(new_test.dtype) #change type of array using dtype of another array
result[0] = 100.0

print('\n Updated result: \n', result) #showing astype returns a new copy and not a reference of the data
print('\n Unchanged test array: \n', test)


Original new_test array:  [10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]

Original test array: 
 [[0. 0. 0.]
 [0. 0. 0.]]

 Updated result: 
 [[100. 100. 100.]
 [  0.   0.   0.]]

 Unchanged test array: 
 [[0. 0. 0.]
 [0. 0. 0.]]


[Back to Contents](#top)

<a id="section-3"></a>
<details open> 
<summary> 03 - Arithmetic with Numpy Array</summary> <br>
    <li> Element-wise operation example
    <li> Broadcasting example - with scalars
</details>

In [11]:
# Element-wise operation example

test1 = np.array([1, 2, 3])
test2 = np.array([4, 5, 6])
test3 = test1 + test2
print(test3)

[5 7 9]


In [12]:
# Broadcasting example - with scalars

test1 = np.array([1, 2, 3])
test2 = test1 + 10
print(test2)

[11 12 13]


[Back to Contents](#top)

<a id="section-4"></a>
<details open> 
<summary> 04 - Indexing and Slicing a Numpy Array</summary> <br>
    <li> Indexing example - 1-D and 2-D array
    <li> Slicing example - 1-D and 2-D array
    <li> Slicing does not produce a copy, we need to use copy() method
    <li> Boolean Indexing
    <li> Fancy Indexing
    <li> Swap & Transpose
</details>

<img src='https://wesmckinney.com/book/images/pda3_0401.png'>

In [13]:
# Indexing example - 1-D and 2-D array

test_1d = np.arange(10)
test_2d = np.arange(10).reshape(2,5)
print('\nPrinting test_1d: ', test_1d)
print('\nPrinting test_2d: \n', test_2d)

print('\nIndexing examples:')
print('Indexing using single index: ', test_1d[1])
print('Indexing using two-dimensional index: ', test_2d[1][2])
print('Indexing using two-dimensional index: (alternate method)', test_2d[1,2]) #two ways to index, using [][] vs [,]


Printing test_1d:  [0 1 2 3 4 5 6 7 8 9]

Printing test_2d: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Indexing examples:
Indexing using single index:  1
Indexing using two-dimensional index:  7
Indexing using two-dimensional index: (alternate method) 7


<img src='https://wesmckinney.com/book/images/pda3_0402.png'>

In [14]:
# Slicing example - 1-D and 2-D array

test_1d = np.arange(10)
test_2d = np.arange(10).reshape(2,5)

print('\nPrinting test_1d: ', test_1d)
print('\nPrinting test_2d: \n', test_2d)

print('\n1-D examples:')
print('Result of test_1d[1:5]: ', test_1d[1:5])
print('Result of test_1d[:5]: ', test_1d[:5])
print('Result of test_1d[5:]: ', test_1d[5:])
print('Result of test_1d[::2]: ', test_1d[::2])

print('\n2-D examples:')
print('Result of test_2d[1:2,1:3]:', test_2d[1:2,2:3])
print('Result of test_2d[1:,:3]:', test_2d[1:,:3])
print('Result of test_2d[:,1:]:\n', test_2d[:,1:])


Printing test_1d:  [0 1 2 3 4 5 6 7 8 9]

Printing test_2d: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

1-D examples:
Result of test_1d[1:5]:  [1 2 3 4]
Result of test_1d[:5]:  [0 1 2 3 4]
Result of test_1d[5:]:  [5 6 7 8 9]
Result of test_1d[::2]:  [0 2 4 6 8]

2-D examples:
Result of test_2d[1:2,1:3]: [[7]]
Result of test_2d[1:,:3]: [[5 6 7]]
Result of test_2d[:,1:]:
 [[1 2 3 4]
 [6 7 8 9]]


In [15]:
# Slicing does not produce a copy, we need to use copy() method

test1 = np.arange(10)
test1_ref = test1[:]
test1_copy = test1.copy()

test1_ref[:] = 1
print('Original test1: ', test1)
print('Sliced data: ', test1_ref)
print('Copied data: ', test1_copy)

Original test1:  [1 1 1 1 1 1 1 1 1 1]
Sliced data:  [1 1 1 1 1 1 1 1 1 1]
Copied data:  [0 1 2 3 4 5 6 7 8 9]


In [16]:
# Boolean Indexing

test1 = np.arange(10)
cond = test1>5

# Usage of operators ~, | and &
print('Result of test1[cond]: ', test1[cond])
print('Result of test1[~cond]: ', test1[~cond])
print('Result of test1[(test1%2==0) & (test1>5)]: ', test1[(test1%2==0) & (test1>5)])
print('Result of test1[(test1%2==0) | (test1>5)]: ', test1[(test1%2==0) | (test1>5)])

Result of test1[cond]:  [6 7 8 9]
Result of test1[~cond]:  [0 1 2 3 4 5]
Result of test1[(test1%2==0) & (test1>5)]:  [6 8]
Result of test1[(test1%2==0) | (test1>5)]:  [0 2 4 6 7 8 9]


In [17]:
# Fancy Indexing

test_1d = np.random.rand(20)
one_d = [1,2,3]

print("1-D example:")
print(test_1d)
print(test_1d[one_d])

test_2d = test_1d.reshape(10,2)
print("\n2-D example:")
print(test_2d)
row_index = np.array([0,1])
col_index = np.array([1,1])

print('\nResults from using row_index, col_index: ')
print(test_2d[row_index, col_index]) #elements from (0,1) and (1,1) are returned which is a 1-D array

1-D example:
[0.22016026 0.23823635 0.99974371 0.4531932  0.36969712 0.54621143
 0.34372777 0.47394042 0.40291294 0.52784093 0.37846281 0.88526454
 0.95275998 0.95415104 0.64341469 0.81208862 0.7611712  0.86280229
 0.40326255 0.74923473]
[0.23823635 0.99974371 0.4531932 ]

2-D example:
[[0.22016026 0.23823635]
 [0.99974371 0.4531932 ]
 [0.36969712 0.54621143]
 [0.34372777 0.47394042]
 [0.40291294 0.52784093]
 [0.37846281 0.88526454]
 [0.95275998 0.95415104]
 [0.64341469 0.81208862]
 [0.7611712  0.86280229]
 [0.40326255 0.74923473]]

Results from using row_index, col_index: 
[0.23823635 0.4531932 ]


In [18]:
# Swap & Transpose

arr_2d = np.arange(5).reshape(1,5)
print('\nOriginal arr_2d:\n',arr_2d)
print('\nTranspose of arr_2d:\n', arr_2d.T)

arr_3d = np.arange(10).reshape(2,5,1)
print('\nOriginal arr_3d:\n',arr_3d)
print('\nSwap axes of arr_3d:\n',arr_3d.swapaxes(1,2))


Original arr_2d:
 [[0 1 2 3 4]]

Transpose of arr_2d:
 [[0]
 [1]
 [2]
 [3]
 [4]]

Original arr_3d:
 [[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]

Swap axes of arr_3d:
 [[[0 1 2 3 4]]

 [[5 6 7 8 9]]]


[Back to Contents](#top)

<a id="section-5"></a>
<details open> 
<summary> 05 - Universal functions</summary> <br>
    <li> Unary functions examples - abs(), sqrt(), exp(), log(), sign()
    <li> Unary functions examples - ceil(), floor(), modf()
    <li> Binary functions examples - add(), subtract(), multiply(), divide(), power(), floor_divide(), maximum(), minimum()
</details>

<b>Unary Functions

| Function|	Description|
|-------|------|
|abs, fabs|	Compute the absolute value element-wise for integer, floating-point, or complex values
|sqrt|	Compute the square root of each element (equivalent to arr ** 0.5)
|square|	Compute the square of each element (equivalent to arr ** 2)
|exp|	Compute the exponent ex of each element
|log, log10, log2, log1p|	Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively
|sign|	Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)
|ceil|	Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)
|floor|	Compute the floor of each element (i.e., the largest integer less than or equal to each element)
|rint|	Round elements to the nearest integer, preserving the dtype
|modf|	Return fractional and integral parts of array as separate arrays
|isnan|	Return Boolean array indicating whether each value is NaN (Not a Number)
|isfinite, isinf|	Return Boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively
|cos, cosh, sin, sinh, tan, tanh|	Regular and hyperbolic trigonometric functions
|arccos, arccosh, arcsin, arcsinh, arctan, arctanh|	Inverse trigonometric functions
|logical_not|	Compute truth value of not x element-wise (equivalent to ~arr)

In [19]:
# Unary functions examples - abs(), sqrt(), exp(), log(), sign()

test = np.random.randint(low=-10,high=10,size=10)   
print("\nTest:\n")
print(test)



Test:

[ 3 -2 -6 -2  0 -1  8 -2 -5  5]


In [20]:

# abs
print(np.abs(test))


[3 2 6 2 0 1 8 2 5 5]


In [21]:

# sqrt
print(np.sqrt(test))


[1.73205081        nan        nan        nan 0.                nan
 2.82842712        nan        nan 2.23606798]


/var/folders/sf/g6jv44b509jdvsxk1xfmb0nc0000gn/T/ipykernel_16861/1352795526.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(test))


In [22]:

# square
print(np.square(test))


[ 9  4 36  4  0  1 64  4 25 25]


In [23]:

# exp
print(np.exp(test))


[2.00855369e+01 1.35335283e-01 2.47875218e-03 1.35335283e-01
 1.00000000e+00 3.67879441e-01 2.98095799e+03 1.35335283e-01
 6.73794700e-03 1.48413159e+02]


In [24]:

# log
print(np.log(test))


[1.09861229        nan        nan        nan       -inf        nan
 2.07944154        nan        nan 1.60943791]


/var/folders/sf/g6jv44b509jdvsxk1xfmb0nc0000gn/T/ipykernel_16861/574345675.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(test))
/var/folders/sf/g6jv44b509jdvsxk1xfmb0nc0000gn/T/ipykernel_16861/574345675.py:2: RuntimeWarning: invalid value encountered in log
  print(np.log(test))


In [25]:

# sign
print(np.sign(test))

[ 1 -1 -1 -1  0 -1  1 -1 -1  1]


In [26]:
# Unary functions examples - ceil(), floor(), modf()

print("\nTest:\n")
test = np.random.rand(10)
print(test)

# ceil
print(np.ceil(test))

# floor
print(np.floor(test))



Test:

[0.33402101 0.48289498 0.82015748 0.32696116 0.47790256 0.2972111
 0.73730451 0.81700295 0.31649838 0.95833728]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
# modf
arr = np.array([3.14, -2.7, 5.5, 0.8])
frac_part, int_part = np.modf(arr)
print(frac_part, int_part)

[ 0.14 -0.7   0.5   0.8 ] [ 3. -2.  5.  0.]


<b>Binary Functions

|Function|	Description|
|--|--|
|add|	Add corresponding elements in arrays
|subtract|	Subtract elements in second array from first array
|multiply|	Multiply array elements
|divide, floor_divide|	Divide or floor divide (truncating the remainder)
|power|	Raise elements in first array to powers indicated in second array
|maximum, fmax|	Element-wise maximum; fmax ignores NaN
|minimum, fmin|	Element-wise minimum; fmin ignores NaN
|mod|	Element-wise modulus (remainder of division)
|copysign|	Copy sign of values in second argument to values in first argument
|greater, greater_equal, less, less_equal, equal, not_equal|	Perform element-wise comparison, yielding Boolean array (equivalent to infix operators >, >=, <, <=, ==, !=)
|logical_and|	Compute element-wise truth value of AND (&) logical operation
|logical_or|	Compute element-wise truth value of OR (|) logical operation
|logical_xor|	Compute element-wise truth value of XOR (^) logical operation

In [28]:
# Binary functions examples - add(), subtract(), multiply(), divide(), power(), floor_divide(), maximum(), minimum()

test1 = np.array([1,2,3])
test2 = np.array([4,5,6])

# add
print(np.add(test1, test2))


[5 7 9]


In [29]:

# subtract
print(np.subtract(test1, test2))


[-3 -3 -3]


In [30]:

# multiply
print(np.multiply(test1, test2))


[ 4 10 18]


In [31]:

# divide
print(np.divide(test1, test2))


[0.25 0.4  0.5 ]


In [32]:

# power
print(np.power(test1, test2))


[  1  32 729]


In [33]:

# floor division
print(np.floor_divide(test1, test2))


[0 0 0]


In [34]:

# maximum
print(np.maximum(test1, test2))


[4 5 6]


In [35]:

# minimum
print(np.minimum(test1, test2))


[1 2 3]


[Back to Contents](#top)

<a id="section-6"></a>
<details open> 
<summary> 06 - Array Oriented Programming with Arrays</summary> <br>
    <li> Expressing conditional logic as array operations
    <li> Mathematical and statistical methods
    <li> Methods for boolean arrays - any(),all()
    <li> Sorting
    <li> Set Operations - unique(), intersect1d(), union1d(), in1d(), setdiff1d(), setxor1d()
</details>

In [36]:
# Expressing conditional logic as array operations

test1 = np.arange(10)
test2 = np.arange(11,21)
print('Original test1: ', test1)
print('Original test2: ', test2)

cond = (test1 % 3 == 0) | (test2 % 2 == 0)
print('Condition: ',cond)
result = np.where(cond, test1, test2) #pick test1 if condition is true, otherwise pick test2
print('Result: ',result)


Original test1:  [0 1 2 3 4 5 6 7 8 9]
Original test2:  [11 12 13 14 15 16 17 18 19 20]
Condition:  [ True  True False  True False  True  True  True False  True]
Result:  [ 0  1 13  3 15  5  6  7 19  9]


<b> Mathematical and statistical methods

|Method|	Description|
|--|--|
|sum|	Sum of all the elements in the array or along an axis; zero-length arrays have sum 0
|mean|	Arithmetic mean; invalid (returns NaN) on zero-length arrays
|std, var|	Standard deviation and variance, respectively
|min, max|	Minimum and maximum
|argmin, argmax|	Indices of minimum and maximum elements, respectively
|cumsum|	Cumulative sum of elements starting from 0
|cumprod|	Cumulative product of elements starting from 1

In [37]:
# Mathematical and statistical methods

test_1d = np.arange(10)
print('Original test_1d: ',test_1d)
print('Printing test_1d.sum(): ',test_1d.sum())

test_2d = np.arange(10).reshape(2,5)
print('\nPrinting test_2d: \n', test_2d)
print('\nPrinting test_2d.sum(): \n',  test_2d.sum())
print('\nPrinting test_2d.sum(axis=0): \n', test_2d.sum(axis=0))

# A few other examples - mean(), std(), max(), min(), argmax(), cumsum(), cumprod()
print('\nFew other examples:')
print('Printing test_1d.mean(): ',test_1d.mean())
print('Printing test_1d.std(): ',test_1d.std())
print('Printing test_1d.var(): ',test_1d.var())
print('Printing test_1d.max(): ',test_1d.max())
print('Printing test_1d.min(): ', test_1d.min())
print('Printing test_1d.argmax(): ', test_1d.argmax())
print('Printing test_1d.argmin(): ', test_1d.argmin())
print('Printing test_1d.cumsum(): ', test_1d.cumsum())
print('Printing test_1d.cumprod(): ', test_1d.cumprod())


Original test_1d:  [0 1 2 3 4 5 6 7 8 9]
Printing test_1d.sum():  45

Printing test_2d: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Printing test_2d.sum(): 
 45

Printing test_2d.sum(axis=0): 
 [ 5  7  9 11 13]

Few other examples:
Printing test_1d.mean():  4.5
Printing test_1d.std():  2.8722813232690143
Printing test_1d.var():  8.25
Printing test_1d.max():  9
Printing test_1d.min():  0
Printing test_1d.argmax():  9
Printing test_1d.argmin():  0
Printing test_1d.cumsum():  [ 0  1  3  6 10 15 21 28 36 45]
Printing test_1d.cumprod():  [0 0 0 0 0 0 0 0 0 0]


In [38]:
# Methods for boolean arrays - any(),all()

test_1d = np.array([True, False, True])

print('Printing test_1d.sum(): ',test_1d.sum())
print('Printing test_1d.any(): ',test_1d.any())
print('Printing test_1d.all(): ',test_1d.all())

Printing test_1d.sum():  2
Printing test_1d.any():  True
Printing test_1d.all():  False


In [39]:
# Sorting

test1 = np.random.randn(5)
print('Original test1: ',test1)
test1.sort()
print('Sorted test1: ',test1)

test2 = np.random.randn(5)
print('Original test2: ',test2)
print('Printing np.sort(test2): ',np.sort(test2)) #using top level np.methods do not change the array inplace
print('Printing test2 again: ',test2)

Original test1:  [-0.09211114 -0.33772469  1.31466166 -2.0265822  -1.56318465]
Sorted test1:  [-2.0265822  -1.56318465 -0.33772469 -0.09211114  1.31466166]
Original test2:  [-0.20867509  0.75423659 -0.00626008 -2.03893214  0.12657572]
Printing np.sort(test2):  [-2.03893214 -0.20867509 -0.00626008  0.12657572  0.75423659]
Printing test2 again:  [-0.20867509  0.75423659 -0.00626008 -2.03893214  0.12657572]


<b>Set Operations

|Method|	Description|
|--|--|
|unique(x)|	Compute the sorted, unique elements in x
|intersect1d(x, y)|	Compute the sorted, common elements in x and y
|union1d(x, y)|	Compute the sorted union of elements
|in1d(x, y)|	Compute a Boolean array indicating whether each element of x is contained in y
|setdiff1d(x, y)|	Set difference, elements in x that are not in y
|setxor1d(x, y)|	Set symmetric differences; elements that are in either of the arrays, but not both

In [40]:
# Set Operations - unique(), intersect1d(), union1d(), in1d(), setdiff1d(), setxor1d() 

# unique
test1 = np.array([1,2,3,1])
print(np.unique(test1))

[1 2 3]


In [41]:
# intersect1d
test2 = np.array([1,2,4])
print(np.intersect1d(test1, test2))


[1 2]


In [42]:
# union1d
print(np.union1d(test1, test2))


[1 2 3 4]


In [43]:
# in1d
print(np.in1d(test1, test2))


[ True  True False  True]


In [44]:
# setdiff1d
print(np.setdiff1d(test1, test2))


[3]


In [45]:
# setxor1d
print(np.setxor1d(test1, test2))

[3 4]


[Back to Contents](#top)

<a id="section-7"></a>
<details open> 
<summary> 07 - Linear Algebra</summary> <br>
    <li>Dot product - multiple ways
    <li>Inverse of a matrix
</details>

|Function|	Description|
|--|--|
|diag|	Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal
|dot|	Matrix multiplication
|trace|	Compute the sum of the diagonal elements
|det|	Compute the matrix determinant
|eig|	Compute the eigenvalues and eigenvectors of a square matrix
|inv|	Compute the inverse of a square matrix
|pinv|	Compute the Moore-Penrose pseudoinverse of a matrix
|qr|	Compute the QR decomposition
|svd|	Compute the singular value decomposition (SVD)
|solve|	Solve the linear system Ax = b for x, where A is a square matrix
|lstsq|	Compute the least-squares solution to Ax = b

In [46]:
# Dot product - multiple ways

x = np.array([1,2])
y = np.array([3,4])

print(x.dot(y))
print(np.dot(x,y))
print(x@y)

11
11
11


In [47]:
# Inverse of a matrix

from numpy.linalg import inv

x = np.arange(4).reshape(2,2)
print(inv(x))

[[-1.5  0.5]
 [ 1.   0. ]]


[Back to Contents](#top)

<a id="section-8"></a>
<details open> 
<summary> 08 - Pseudorandom Number Generation</summary> <br>
    <li>Random nos. generation and using seed()
    <li>Other examples - 
</details>

In [48]:
# Random nos. generation and using seed()

dist = np.random.normal(size=(4,4))
print(dist)

np.random.seed(1)
dist = np.random.normal(size=(4,4))
print('\n')
print(dist)

rng = np.random.RandomState(10)
print('\n')
print(rng.randn(10))


[[ 0.66053184 -0.04918544 -1.1879332  -0.58665286]
 [ 1.83998721 -1.35591601  1.50028918  1.12069971]
 [ 1.91984279 -0.82113191  1.98826613  0.59578841]
 [ 1.40077048  0.92004742  1.24622566  0.53250695]]


[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]
 [ 0.3190391  -0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944 -1.09989127]]


[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556
  0.26551159  0.10854853  0.00429143 -0.17460021]


In [49]:
# Other examples - permutation(), shuffle(), binomial(), normal(), uniform()

np.random.seed(1)
dist = np.random.randn(10)
print(dist)

print('\nPerumutation of array: \n', np.random.permutation(dist))
np.random.shuffle(dist)
print('\nShuffling of array: \n', dist)
print('\nBinomial distribution: \n', np.random.binomial(10, 0.5))
print('\nNormal distribution: \n', np.random.normal(10, 2))
print('\nUniform distribution: \n', np.random.uniform(10, 2))


[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]

Perumutation of array: 
 [ 0.3190391  -1.07296862 -2.3015387  -0.24937038  1.62434536  1.74481176
 -0.61175641 -0.7612069   0.86540763 -0.52817175]

Shuffling of array: 
 [-0.52817175  0.86540763 -1.07296862  1.62434536  1.74481176 -0.61175641
 -2.3015387   0.3190391  -0.7612069  -0.24937038]

Binomial distribution: 
 3

Normal distribution: 
 11.067621824565125

Uniform distribution: 
 5.734677720215863


[Back to Contents](#top)