<a id="top"></a>

### Contents
- [01 - Numpy Package](#section-1) 
- [02 - Creating a Numpy Array](#section-2) 
- [03 - Arithmetic with Numpy Array](#section-3) 
- [04 - Indexing and Slicing a Numpy Array](#section-4)
- [05 - Universal Functions](#section-5)  
- [06 - Array Oriented Programming with Arrays](#section-6)
- [07 - Linear Algebra](#section-7) 
- [08 - Pseudorandom Number Generation](#section-8)

<a id="section-1"></a>
<details open> 
<summary> 01 - Numpy Package </summary> 
</details>

In [1]:
try:
    import numpy
except ImportError:
    !pip install numpy
else:
    import numpy as np


[Back to Contents](#top)

<a id="section-2"></a>
<details open> 
<summary> 02 - Creating a Numpy Array </summary> <br>
    <li> Attributes of a simple Numpy array - shape, ndim, dtype
    <li> Creating a Numpy arry using functions - array(), zeros(), ones(), empty(), arange(), astype(), full(), eye()
</details>

In [2]:
# Attributes of a simple Numpy array - shape, ndim, dtype

test = np.array([1, 2, 3])

print(test.shape)
print(test.ndim)
print(test.dtype)

(3,)
1
int64


In [71]:
# Creating a Numpy arry using functions - array(), zeros(), ones(), empty(), arange(), astype(), full(), eye()

test = np.array([1, 2, 3])
print(test)

test = np.zeros((2, 3)) #input is tuple which indicates shape - rows and columns
print(test)

test = np.ones((2, 3))
print(test)

new_test = np.empty((2, 3)) #empty does not return an array with 0s
print(new_test)

test = np.arange(10) #arange is numpy equivalent of range()
print(test)

new_test = np.arange(10.0, 20.9)
print(new_test)
result = test.astype(new_test.dtype) #change type of array using dtype of another array
result[0] = 100.0

print(result) #showing astype returns a new copy and not a reference of the data
print(test)

full_example = np.full((2, 3), 10) #filling an numpy array with a particular shape with a given value
print(full_example)

eye_example = np.eye(3) #identity matrix
print(eye_example)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
[100.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
[0 1 2 3 4 5 6 7 8 9]
[[10 10 10]
 [10 10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[Back to Contents](#top)

<a id="section-3"></a>
<details open> 
<summary> 03 - Arithmetic with Numpy Array</summary> <br>
    <li> Element-wise operation example
    <li> Broadcasting example - with scalars
</details>

In [4]:
# Element-wise operation example

test1 = np.array([1, 2, 3])
test2 = np.array([4, 5, 6])
test3 = test1 + test2
print(test3)

[5 7 9]


In [5]:
# Broadcasting example - with scalars

test1 = np.array([1, 2, 3])
test2 = test1 + 10
print(test2)

[11 12 13]


[Back to Contents](#top)

<a id="section-4"></a>
<details open> 
<summary> 04 - Indexing and Slicing a Numpy Array</summary> <br>
    <li> Indexing example - 1-D and 2-D array
    <li> Slicing example - 1-D and 2-D array
    <li> Slicing does not produce a copy, we need to use copy() method
    <li> Boolean Indexing
    <li> Fancy Indexing
    <li> Swap & Transpose
</details>

In [ ]:
# Indexing example - 1-D and 2-D array

test_1d = np.arange(10)
test_2d = np.arange(10).reshape(2,5)
print(test_1d)
print(test_2d)

print(test_1d[1])
print(test_2d[1][2])
print(test_2d[1,2]) #two ways to index, using [][] vs [,]

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
1
7
7


In [73]:
# Slicing example - 1-D and 2-D array

test_1d = np.arange(10)
test_2d = np.arange(10).reshape(2,5)
print(test_1d)
print(test_2d)

print('\n1-D examples:')
print(test_1d[1:5])
print(test_1d[:5])
print(test_1d[5:])
print(test_1d[::2])

print('\n2-D examples:')
print(test_2d[1:2,2:3])
print("\n")
print(test_2d[1:,:3])
print("\n")
print(test_2d[:,1:])

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]

1-D examples:
[1 2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]

2-D examples:
[[7]]


[[5 6 7]]


[[1 2 3 4]
 [6 7 8 9]]


In [ ]:
# Slicing does not produce a copy, we need to use copy() method

test1 = np.arange(10)
test1_ref = test1[:]
test1_copy = test1.copy()

test1_ref[:] = 1
print(test1)
print(test1_ref)
print(test1_copy)

[1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Boolean Indexing

test1 = np.arange(10)
cond = test1>5

# Usage of operators ~, | and &
print(test1[cond])
print(test1[~cond])
print(test1[(test1%2==0) & (test1>5)])
print(test1[(test1%2==0) | (test1>5)])

[6 7 8 9]
[0 1 2 3 4 5]
[6 8]
[0 2 4 6 7 8 9]


In [72]:
# Fancy Indexing

test_1d = np.random.rand(20)
one_d = [1,2,3]

print("1-D example:")
print(test_1d)
print(test_1d[one_d])

test_2d = test_1d.reshape(10,2)
print("\n2-D example:")
print(test_2d)
row_index = np.array([0,1])
col_index = np.array([1,1])

test_2d[row_index, col_index] #elements from (0,1) and (1,1) are returned which is a 1-D array

1-D example:
[0.30628321 0.75963217 0.56352703 0.69525926 0.47023647 0.75310944
 0.15626232 0.47058819 0.20556788 0.36565755 0.40402486 0.42035183
 0.44097561 0.45417186 0.52206254 0.52108887 0.74354321 0.75223785
 0.71327071 0.78280183]
[0.75963217 0.56352703 0.69525926]

2-D example
[[0.30628321 0.75963217]
 [0.56352703 0.69525926]
 [0.47023647 0.75310944]
 [0.15626232 0.47058819]
 [0.20556788 0.36565755]
 [0.40402486 0.42035183]
 [0.44097561 0.45417186]
 [0.52206254 0.52108887]
 [0.74354321 0.75223785]
 [0.71327071 0.78280183]]


array([0.75963217, 0.69525926])

In [ ]:
# Swap & Transpose

print('Transpose example:')
arr_2d = np.arange(5).reshape(1,5)
print(arr_2d)
print(arr_2d.T)

print('\nSwap example:')
arr_3d = np.arange(10).reshape(2,5,1)
print(arr_3d)
print(arr_3d.swapaxes(1,2))

Transpose example:
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]

Swap example:
[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]]
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]


[Back to Contents](#top)

<a id="section-5"></a>
<details open> 
<summary> 05 - Universal functions</summary> <br>
    <li> Unary functions examples - abs(), sqrt(), exp(), log(), sign()
    <li> Unary functions examples - ceil(), floor(), modf()
    <li> Binary functions examples - add(), subtract(), multiply(), divide(), power(), floor_divide(), maximum(), minimum()
</details>

In [88]:
# Unary functions examples - abs(), sqrt(), exp(), log(), sign()

test = np.random.randint(low=-10,high=10,size=10)   
print("\nTest:\n")
print(test)

# abs
print(np.abs(test))

# sqrt
print(np.sqrt(test))

# square
print(np.square(test))

# exp
print(np.exp(test))

# log
print(np.log(test))

# sign
print(np.sign(test))


Test:

[-10  -3  -6   1   7   0   1   1  -2  -8]
[10  3  6  1  7  0  1  1  2  8]
[       nan        nan        nan 1.         2.64575131 0.
 1.         1.                nan        nan]
[100   9  36   1  49   0   1   1   4  64]
[4.53999298e-05 4.97870684e-02 2.47875218e-03 2.71828183e+00
 1.09663316e+03 1.00000000e+00 2.71828183e+00 2.71828183e+00
 1.35335283e-01 3.35462628e-04]
[       nan        nan        nan 0.         1.94591015       -inf
 0.         0.                nan        nan]
[-1 -1 -1  1  1  0  1  1 -1 -1]


/var/folders/sf/g6jv44b509jdvsxk1xfmb0nc0000gn/T/ipykernel_28310/260354542.py:10: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(test))
/var/folders/sf/g6jv44b509jdvsxk1xfmb0nc0000gn/T/ipykernel_28310/260354542.py:19: RuntimeWarning: divide by zero encountered in log
  print(np.log(test))
/var/folders/sf/g6jv44b509jdvsxk1xfmb0nc0000gn/T/ipykernel_28310/260354542.py:19: RuntimeWarning: invalid value encountered in log
  print(np.log(test))


In [95]:
# Unary functions examples - ceil(), floor(), modf()

print("\nTest:\n")
test = np.random.rand(10)
print(test)

# ceil
print(np.ceil(test))

# floor
print(np.floor(test))

# modf
arr = np.array([3.14, -2.7, 5.5, 0.8])
frac_part, int_part = np.modf(arr)
print(frac_part, int_part)


Test:

[0.82029625 0.19644664 0.7566043  0.91277322 0.54274882 0.94694989
 0.47540473 0.83088774 0.24401987 0.28159937]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.14 -0.7   0.5   0.8 ] [ 3. -2.  5.  0.]


In [96]:
# Binary functions examples - add(), subtract(), multiply(), divide(), power(), floor_divide(), maximum(), minimum()

test1 = np.array([1,2,3])
test2 = np.array([4,5,6])

# add
print(np.add(test1, test2))

# subtract
print(np.subtract(test1, test2))

# multiply
print(np.multiply(test1, test2))

# divide
print(np.divide(test1, test2))

# power
print(np.power(test1, test2))

# floor division
print(np.floor_divide(test1, test2))

# maximum
print(np.maximum(test1, test2))

# minimum
print(np.minimum(test1, test2))


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[0 0 0]
[4 5 6]
[1 2 3]


[Back to Contents](#top)

<a id="section-6"></a>
<details open> 
<summary> 06 - Array Oriented Programming with Arrays</summary> <br>
    <li> Expressing conditional logic as array operations
    <li> Mathematical and statistical methods
    <li> Methods for boolean arrays - any(),all()
    <li> Sorting
    <li> Set Operations - unique(), intersect1d(), union1d(), in1d(), setdiff1d(), setxor1d()
</details>

In [51]:
# Expressing conditional logic as array operations

test1 = np.arange(10)
test2 = np.arange(11,21)
print(test1)
print(test2)

cond = (test1 % 3 == 0) | (test2 % 2 == 0)
print(cond)
result = np.where(cond, test1, test2)
print(result)


[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[ True  True False  True False  True  True  True False  True]
[ 0  1 13  3 15  5  6  7 19  9]


In [98]:
# Mathematical and statistical methods

test_1d = np.arange(10)
print(test_1d)
print(test_1d.sum())

test_2d = np.arange(10).reshape(2,5)
print(test_2d)
print(test_2d.sum())
print(test_2d.sum(axis=0))

# A few other examples - mean(), std(), max(), min(), argmax(), cumsum(), cumprod()
print('\nFew other examples:')
print(test_1d.mean())
print(test_1d.std())
print(test_1d.var())
print(test_1d.max())
print(test_1d.min())
print(test_1d.argmax())
print(test_1d.argmin())
print(test_1d.cumsum())
print(test_1d.cumprod())


[0 1 2 3 4 5 6 7 8 9]
45
[[0 1 2 3 4]
 [5 6 7 8 9]]
45
[ 5  7  9 11 13]

Few other examples:
4.5
2.8722813232690143
8.25
9
0
9
0
[ 0  1  3  6 10 15 21 28 36 45]
[0 0 0 0 0 0 0 0 0 0]


In [57]:
# Methods for boolean arrays - any(),all()

test_1d = np.array([True, False, True])

print(test_1d.sum())
print(test_1d.any())
print(test_1d.all())

2
True
False


In [61]:
# Sorting

test1 = np.random.randn(5)
print(test1)
test1.sort()
print(test1)

test2 = np.random.randn(5)
print(test2)
print(np.sort(test2)) #using top level np.methods do not change the array inplace
print(test2)

[-0.84364025 -0.8058819  -0.49624227  0.35622901 -1.64498714]
[-1.64498714 -0.84364025 -0.8058819  -0.49624227  0.35622901]
[ 2.01061027 -0.90209383  1.22444626  1.48736585 -1.1533248 ]
[-1.1533248  -0.90209383  1.22444626  1.48736585  2.01061027]
[ 2.01061027 -0.90209383  1.22444626  1.48736585 -1.1533248 ]


In [100]:
# Set Operations - unique(), intersect1d(), union1d(), in1d(), setdiff1d(), setxor1d() 

test1 = np.array([1,2,3,1])
print(np.unique(test1))

test2 = np.array([1,2,4])

print(np.intersect1d(test1, test2))
print(np.union1d(test1, test2))
print(np.in1d(test1, test2))
print(np.setdiff1d(test1, test2))
print(np.setxor1d(test1, test2))

[1 2 3]
[1 2]
[1 2 3 4]
[ True  True False  True]
[3]
[3 4]


[Back to Contents](#top)

<a id="section-7"></a>
<details open> 
<summary> 07 - Linear Algebra</summary> <br>
    <li>Dot product - multiple ways
    <li>Inverse of a matrix
</details>

In [65]:
# Dot product - multiple ways

x = np.array([1,2])
y = np.array([3,4])

print(x.dot(y))
print(np.dot(x,y))
print(x@y)

11
11
11


In [69]:
# Inverse of a matrix

from numpy.linalg import inv

x = np.arange(4).reshape(2,2)
print(inv(x))

[[-1.5  0.5]
 [ 1.   0. ]]


[Back to Contents](#top)

<a id="section-8"></a>
<details open> 
<summary> 08 - Pseudorandom Number Generation</summary> <br>
    <li>Random nos. generation and using seed()
    <li>Other examples - 
</details>

In [104]:
# Random nos. generation and using seed()

dist = np.random.normal(size=(4,4))
print(dist)

np.random.seed(1)
dist = np.random.normal(size=(4,4))
print('\n')
print(dist)

rng = np.random.RandomState(10)
print('\n')
print(rng.randn(10))


[[-0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434]
 [ 0.90085595 -0.68372786 -0.12289023 -0.93576943]
 [-0.26788808  0.53035547 -0.69166075 -0.39675353]]


[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]
 [ 0.3190391  -0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944 -1.09989127]]


[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597 -0.72008556
  0.26551159  0.10854853  0.00429143 -0.17460021]


In [110]:
# Other examples - permutation(), shuffle(), binomial(), normal(), uniform()

np.random.seed(1)
dist = np.random.randn(10)
print(dist)

print('\n')
print(np.random.permutation(dist))
print('\n')
np.random.shuffle(dist)
print(dist)
print('\n')
print(np.random.binomial(10, 0.5))
print('\n')
print(np.random.normal(10, 2))
print('\n')
print(np.random.uniform(10, 2))


[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
  1.74481176 -0.7612069   0.3190391  -0.24937038]


[ 0.3190391  -1.07296862 -2.3015387  -0.24937038  1.62434536  1.74481176
 -0.61175641 -0.7612069   0.86540763 -0.52817175]


[-0.52817175  0.86540763 -1.07296862  1.62434536  1.74481176 -0.61175641
 -2.3015387   0.3190391  -0.7612069  -0.24937038]


3


11.067621824565125


5.734677720215863


[Back to Contents](#top)